server:
  shutdown: graceful
  port: 8080
spring:
  datasource:
    url: ENC(dJWb1lWuXwIBdxpLkrvVViTNygowQjK/h/NYCH8ytSuBHoo+CaCvRdQMhqlVaTKbrRsy1wIJTiCB3FddPAY6uMGhDnJp1ZGzMiWVB2rVhvRdNtMS+T8mbvRATEkpUhoO2MeleHJVFSxgkvj5u2t+9w==)
    username: ENC(i7kaP0sYfSmNlzMnGHQPaZ88RAQcWfjUglGpJHOCl21jZxpvEsbJVJMkDx4PM6U9)
    password: ENC(QtDhVW7qSMvUq9q+OUSGGhJbBYqd80mL1lNBu12pUV1hTf+HDnPJsKBTJBNb3PgG)
    driver-class-name: com.mysql.cj.jdbc.Driver