server:
  shutdown: graceful
  port: 8080
spring:
  datasource:
    url: ENC(cxr5XW73EIYw9MBII5luBdJEdnZ4FbM2PVyde3t3I2/AQ4SgIA3ZZ6F29/768Vf2G+evqC5KI4vthzWb2DiNdtEFwv10MTtxSRQRBX9HJB2Q8aEDNHu1Im2/7+VzK/wlwIJXiHNSugI0UN1+6V0hug==)
    username: ENC(LSNdBGht4peMFcdBcfJtvhaN9OIwkcKkz+Z5vXvkeASY5zRGCFmVE9MrkaPwPYFR)
    password: ENC(HbBQ8/OBU84rXwP4aBRaUO2fZwhv7WC4nHvBbTXaL8t7keVScnGqwuQqoJNfa11N)
    driver-class-name: com.mysql.cj.jdbc.Driver

file:
  path: C:\\file_image\\
